service: recoil-design-tool

app: recoil-design-tool
org: jacquesblom

frameworkVersion: '2'
plugins:
    - serverless-plugin-typescript

provider:
    name: aws
    runtime: nodejs12.x

    environment:
        DYNAMODB_TABLE_IMAGES: ${self:service}-images-${self:provider.stage}
        DYNAMODB_TABLE_STATE: ${self:service}-state-${self:provider.stage}

    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:GetItem
              - dynamodb:UpdateItem
              - dynamodb:PutItem
          Resource:
              - {'Fn::GetAtt': ['DynamoDBImages', 'Arn']}
              - {'Fn::GetAtt': ['DynamoDBState', 'Arn']}

functions:
    image-details:
        handler: handlers/image-details.handler
        events:
            - http:
                  path: image-details
                  method: get
        environment:
            DYNAMODB_TABLE_IMAGES: ${self:provider.environment.DYNAMODB_TABLE_IMAGES}
    random-image:
        handler: handlers/random-image.handler
        events:
            - http:
                  path: random-image
                  method: get
        environment:
            DYNAMODB_TABLE_IMAGES: ${self:provider.environment.DYNAMODB_TABLE_IMAGES}
    store-state:
        handler: handlers/store-state.handler
        events:
            - http:
                  path: store-state
                  method: post
        environment:
            DYNAMODB_TABLE_STATE: ${self:provider.environment.DYNAMODB_TABLE_STATE}

resources:
    Resources:
        DynamoDBImages:
            Type: 'AWS::DynamoDB::Table'
            Properties:
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
                TableName: ${self:provider.environment.DYNAMODB_TABLE_IMAGES}
        DynamoDBState:
            Type: 'AWS::DynamoDB::Table'
            Properties:
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
                TableName: ${self:provider.environment.DYNAMODB_TABLE_STATE}
